[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "noshow-iq-s"
version = "0.1.0"
description = "A prediction API for medical appointment no-shows"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
  { name = "kiran" }
]

dependencies = [
  "fastapi",
  "uvicorn",
  "pandas",
  "scikit-learn",
  "imbalanced-learn",
  "joblib",
  "pymongo",
  "python-dotenv"
]

[tool.setuptools]
packages = ["noshow_iq"]

[tool.pytest.ini_options]
testpaths = ["tests"]